apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: cloudnative-app
spec:
  type: LoadBalancer
  selector:
    app: cloudnativewebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   # ✅ must match containerPort
